"""add index to title_id and title search columns

Revision ID: fd569b5b222a
Revises: 08e261416d42
Create Date: 2026-08-19 14:38:21.612172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd569b5b222a'
down_revision = '08e261416d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identifiers', schema=None) as batch_op:
        batch_op.create_index('idx_identifier_type_value', ['id_type', 'id_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_identifiers_title_id'), ['title_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('identifiers_title_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'titles', ['title_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titles_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titles_title'))

    with op.batch_alter_table('identifiers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('identifiers_title_id_fkey'), 'titles', ['title_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_identifiers_title_id'))
        batch_op.drop_index('idx_identifier_type_value')

    # ### end Alembic commands ###
